### ISSUE TITLE
duration of null

### ISSUE THREAD

**Issue by hmdshariati** [jibon57/bbb-recorder#100]
I don't know why duration of document.getElementById("vjs_video_3_html5_api") return error!?

I replace it with return 10 and script run successfully? what's the usage of recDuration? is it necessary? (maybe for find the endig of videos)

how can I resolve this issue:

```
Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'duration')
    at __puppeteer_evaluation_script__:2:72
    at ExecutionContext._evaluateInternal (/var/www/bbb-recorder/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async ExecutionContext.evaluate (/var/www/bbb-recorder/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async main (/var/www/bbb-recorder/export.js:136:27)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/var/www/bbb-recorder/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/var/www/bbb-recorder/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
  -- ASYNC --
    at Frame.<anonymous> (/var/www/bbb-recorder/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/var/www/bbb-recorder/node_modules/puppeteer/lib/Page.js:860:43)
    at Page.<anonymous> (/var/www/bbb-recorder/node_modules/puppeteer/lib/helper.js:112:23)
    at main (/var/www/bbb-recorder/export.js:136:38)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by redesufpel** [comment]
@hmdshariati any clue about it ?

**Comment by redesufpel** [comment]
@hmdshariati as you can see in export.js line 136 the variable 'recDuration' are the value used if the current duration passed to the function was set to 0 or if greater than recDuration (means the real duration of video).

But I don't have any clue how to fix this. I just returned the same value of duration to recDuration by now.

**Comment by aguerson** [comment]
Could it be a puppeter problem ?

**Comment by aguerson** [comment]
I found a way to find the good duration

`ffprobe -i https://$host.$domain/presentation/$idpres/video/webcams.mp4 -show_entries format=duration -v quiet -of csv="p=0"`

**Comment by kiakeykhosravi** [comment]
@aguerson tnx
