### ISSUE TITLE
Error: ENOENT: no such file or directory, mkdir

### ISSUE THREAD

**Issue by kaplanemre** [jibon57/bbb-recorder#104]
Hi, 
Why am I getting the following error, can you help?

{ Error: ENOENT: no such file or directory, mkdir '/var/www/bigbluebutton-default/record'
    at Object.mkdirSync (fs.js:757:3)
    at convertAndCopy (/home/emre/Desktop/bbb-recorder-master/export.js:215:12)
    at main (/home/emre/Desktop/bbb-recorder-master/export.js:187:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/var/www/bigbluebutton-default/record' }

**Comment by kiakeykhosravi** [comment]
app is expecting this '/var/www/bigbluebutton-default/record'  but there is no such directory in your file structure so you either should use sudo command to run the app or create that directory manually.
