### ISSUE TITLE
How can i run this script my local Ubuntu 

### ISSUE THREAD

**Issue by mustifanci** [jibon57/bbb-recorder#109]
Hi i install every depencies but it doesnt work in local computer . İt give a error 
`Error: ENOENT: no such file or directory, mkdir '/var/www/bigbluebutton-default/record'
    at Object.mkdirSync (fs.js:921:3)
    at convertAndCopy (/home/mustafa/Videolar/bbb-render-master/bbb-recorder/export.js:215:12)
    at main (/home/mustafa/Videolar/bbb-render-master/bbb-recorder/export.js:187:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/var/www/bigbluebutton-default/record'
}
`
 Can i run this project on my local PC

**Comment by jibon57** [comment]
change value here: https://github.com/jibon57/bbb-recorder/blob/7f3ef4439b8754c082e18681396d2abbb4896233/.env.example#L5

OR

`sudo mkdir -p /var/www/bigbluebutton-default/record`
recordings will be store there
