### ISSUE TITLE
Errors while running the service

### ISSUE THREAD

**Issue by ramakirankumar** [jibon57/bbb-recorder#15]
Hi,

Followed the document and deployed accordingly in the same server where BBB is installed. however when i start "node ffmpegServer.js", iam getting the following error:
root@ns107515:~/bbb-recorder# node ffmpegServer.js
Listening...
connection
FFmpeg STDERR: ffmpeg version 4.2.2-1ubuntu1~16.04.york0 Copyright (c) 2000-2019                                                                                                                                                              the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
  configuration: --prefix=/usr --extra-version='1ubuntu1~16.04.york0' --toolchai                                                                                                                                                             n=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux                                                                                                                                                             -gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable                                                                                                                                                             -filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-liba                                                                                                                                                             om --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable                                                                                                                                                             -libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-li                                                                                                                                                             bfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack -                                                                                                                                                             -enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt -                                                                                                                                                             -enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enab                                                                                                                                                             le-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libss                                                                                                                                                             h --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis                                                                                                                                                              --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-l                                                                                                                                                             ibxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-o                                                                                                                                                             mx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1                                                                                                                                                             394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --e                                                                                                                                                             nable-frei0r --enable-libx264 --enable-shared

FFmpeg STDERR:   libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100

However when i checked ./dependencies_check.sh it doesnt returns anything which indicates it has all the necessary required files.

In the other tab, i directly executed Live stream command only but it returned the same error. The BBB setup i have is the standard out of the box setup without any changes.
node liveRTMP.js "https://test.testdomain.com/bigbluebutton/api/join?meetingId=abc-zgm-cqh"
PAGE LOG: FFMPEG_SERVER
{ TimeoutError: waiting for selector "[aria-label="Listen only"]" failed: timeout 30000ms exceeded
    at new WaitTask (/root/bbb-recorder/node_modules/puppeteer/lib/DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (/root/bbb-recorder/node_modules/puppeteer/lib/DOMWorld.js:478:22)
    at DOMWorld.waitForSelector (/root/bbb-recorder/node_modules/puppeteer/lib/DOMWorld.js:432:17)
    at Frame.waitForSelector (/root/bbb-recorder/node_modules/puppeteer/lib/FrameManager.js:627:47)
    at Frame.<anonymous> (/root/bbb-recorder/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.waitForSelector (/root/bbb-recorder/node_modules/puppeteer/lib/Page.js:1122:29)
    at main (/root/bbb-recorder/liveRTMP.js:72:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) name: 'TimeoutError' }

Can you please help to get this resolved. Would like to stream to youtube with the limitations accepted as mentioned in your readme for this tool.

Thank you,
KiranKumar.

**Comment by ramakirankumar** [comment]
Tried with liveJoin.js command and same error exists as below:
root@ns107515:~/bbb-recorder# node liveJoin.js "https://udoevents.udo-now.com/gbluebutton/api/join?meetingId=kom-zgm-cqh"
{ TimeoutError: waiting for selector "[aria-label="Listen only"]" failed: timeout 30000ms exceeded
    at new WaitTask (/root/bbb-recorder/node_modules/puppeteer/lib/DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (/root/bbb-recorder/node_modules/puppeteer/lib/DOMWorld.js:478:22)
    at DOMWorld.waitForSelector (/root/bbb-recorder/node_modules/puppeteer/lib/DOMWorld.js:432:17)
    at Frame.waitForSelector (/root/bbb-recorder/node_modules/puppeteer/lib/FrameManager.js:627:47)
    at Frame.<anonymous> (/root/bbb-recorder/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.waitForSelector (/root/bbb-recorder/node_modules/puppeteer/lib/Page.js:1122:29)
    at main (/root/bbb-recorder/liveJoin.js:68:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) name: 'TimeoutError' }

I checked the server locale and it is en-US itself and language is English itself. When i inspect element the BBB i can see the button for "Listen only" as aria-label="Listen only"

**Comment by ramakirankumar** [comment]
Finally i was able to run both liveJoin.js and also liveRTMP.js from the terminals in ubuntu.. 
It was because i have Greenlight html5 client installed, the url was directing to its home page instead of joining the meeting. With the help of bbb-demos the jsp files, i figured out the join url and used that as argument in liveRTMP and liveJoin. i gave the attendee fullname as "User1".
ex:
https://test.testdomain.com/bigbluebutton/api/join?meetingID=abc-zgm-cqh&fullName=user1&joinViaHtml5=false&password=mp&checksum=38ec951f1a2179af3952803fa0c90a6d496f3a8f7c0921591c1846fcfdef3bb3

But in the config.json file i replaced the "MyKey" with the stream key generated in youtube -> Go Live screen -> stream screen
But i dont see any stream coming to youtube live.

Can you suggest what changes needs to be made to have youtube live? i as moderator started the meeting with webcam enabled and audio running. No other attendees joined so far in this experiment.

Thanks.

**Comment by ramakirankumar** [comment]
Finally able to get the youtube live working. :)

Can we have multiple broadcasts from BBB to make youtube live across multiple youtube channels parallely?
I mean, if user A, user B and user C broadcasts different webinars at a time then can we broadcast User A webinar to youtube live stream StreamA, userB to StreamB, userC to StreamC?
Can you let me know the way forward please.

Thanks,
