### ISSUE TITLE
How to process recording concurrently?

### ISSUE THREAD

**Issue by mabras** [jibon57/bbb-recorder#33]
I am trying to edit export.js to loop on all of my old presentation (BBB recording). I need `export.js` to process at least two presentations in the same time? I have edit `export.js` to process two urls instead of `process.argv`.

Currently I have this:
```
recorder = 0
# looping over my recordings
  if (recorder < 2) {
    recorder +=1

    main(url).then(() => {
      recorder -=1
    })
  }
#
```
On my mac OS everything works just as expected. On my Ubuntu 18.04 server I get this error:

```
Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (/root/bbb-recorder/node_modules/puppeteer/lib/Connection.js:180:29)
    at ExecutionContext._evaluateInternal (/root/bbb-recorder/node_modules/puppeteer/lib/ExecutionContext.js:107:44)
    at ExecutionContext.evaluate (/root/bbb-recorder/node_modules/puppeteer/lib/ExecutionContext.js:48:23)
    at ExecutionContext.<anonymous> (/root/bbb-recorder/node_modules/puppeteer/lib/helper.js:112:23)
    at DOMWorld.evaluate (/root/bbb-recorder/node_modules/puppeteer/lib/DOMWorld.js:112:20)
  -- ASYNC --
    at Frame.<anonymous> (/root/bbb-recorder/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/root/bbb-recorder/node_modules/puppeteer/lib/Page.js:860:43)
    at Page.<anonymous> (/root/bbb-recorder/node_modules/puppeteer/lib/helper.js:112:23)
    at main (/root/bbb-recorder/export.js:136:20)
```

What is problem? Why I am getting different behavior when changing the OS.

Thanks

**Comment by jibon57** [comment]
Try to open each process in separate terminal or can use cron job or remove `xvfb.stopSync()`
