### ISSUE TITLE
page.waitForSelector('html.downloadComplete') does not end.

### ISSUE THREAD

**Issue by henriquebol** [jibon57/bbb-recorder#35]
Is anyone else having the same problem? If I leave it on timeout: 0, it waits endlessly. I'm doing the tests with a 10-second recording, I don't believe it's internet speed.

```
await page.waitForSelector('html.downloadComplete', {timeout: 0})
```

I tested with a timeout (120000ms) with try / catch, returns the TimeoutError and ends.

```
error { TimeoutError: waiting for selector "html.downloadComplete" failed: timeout 120000ms exceeded
    at new WaitTask (/home/hb/projetos/bbb-downloader/node_modules/puppeteer/lib/DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (/home/hb/projetos/bbb-downloader/node_modules/puppeteer/lib/DOMWorld.js:478:22)
    at DOMWorld.waitForSelector (/home/hb/projetos/bbb-downloader/node_modules/puppeteer/lib/DOMWorld.js:432:17)
    at Frame.waitForSelector (/home/hb/projetos/bbb-downloader/node_modules/puppeteer/lib/FrameManager.js:627:47)
    at Frame.<anonymous> (/home/hb/projetos/bbb-downloader/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.waitForSelector (/home/hb/projetos/bbb-downloader/node_modules/puppeteer/lib/Page.js:1122:29)
    at exports.startRecording (/home/hb/projetos/bbb-downloader/src/app/lib/bbb-recorder/recorder.js:139:18)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }

**Comment by jibon57** [comment]
Hi,
This is mean after recording the download was failed. In this line:
https://github.com/jibon57/bbb-recorder/blob/5e30b12f20a8c57bfe8b1eafb9798c0ba0b9b222/background.js#L101
Make sure that Chrome has permission to download files.
