### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property 'duration' of null

### ISSUE THREAD

**Issue by eagleconferencing** [jibon57/bbb-recorder#39]
Getting above error, when using below command
Error: Evaluation failed: TypeError: Cannot read property 'duration' of null

node export.js "https://DOMAIN/playback/presentation/2.0/playback.html?meetingId=7de4746928475b5276e1615ae0a19ed1fc5227a9-1593389262941" 7de4746928475b5276e1615ae0a19ed1fc5227a9-1593389262941.webm 10 true 

I cloned and installed the project today.

**Comment by eagleconferencing** [comment]
Error: Evaluation failed: TypeError: Cannot read property 'duration' of null
    at __puppeteer_evaluation_script__:2:52
    at ExecutionContext._evaluateInternal (/usr/src/bbb-recorder/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/usr/src/bbb-recorder/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async main (/usr/src/bbb-recorder/export.js:110:27)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/usr/src/bbb-recorder/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/usr/src/bbb-recorder/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/usr/src/bbb-recorder/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/usr/src/bbb-recorder/node_modules/puppeteer/lib/Page.js:860:43)
    at Page.<anonymous> (/usr/src/bbb-recorder/node_modules/puppeteer/lib/helper.js:112:23)
    at main (/usr/src/bbb-recorder/export.js:110:38)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by jibon57** [comment]
Make sure the link is valid. Looks like having problem with duration value. You can try without duration set. Or

`node export.js "https://DOMAIN/playback/presentation/2.0/playback.html?meetingId=7de4746928475b5276e1615ae0a19ed1fc5227a9-1593389262941" 7de4746928475b5276e1615ae0a19ed1fc5227a9-1593389262941.webm 0 true`

**Comment by eagleconferencing** [comment]
I even tried with/without 0  nothing is working
everytime getting the same error

**Comment by eagleconferencing** [comment]
Link is valid, i have masked my domain here with DOMAIN

**Comment by hipoloco** [comment]
Are you using a custom playback file? Comment out the following block of code in export.js file and try again setting the duration to 10:

>         // Get recording duration
>         var recDuration = await page.evaluate(() => {
>             return document.getElementById("video").duration;
>         });
>         // If duration was set to 0 or is greater than recDuration, use recDuration value
>         if(duration == 0 || duration > recDuration){
>             duration = recDuration;
>         }

**Comment by eagleconferencing** [comment]
Its not custom file, its bbb file. Working fine now without any changes.
