### ISSUE TITLE
SyntaxError: Unexpected token function after update

### ISSUE THREAD

**Issue by levigo-systems** [jibon57/bbb-recorder#40]
Hello,
we get the following error after updating our os packages:
```
/root/bbb-recorder/export.js:40
async function main() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

```
ii  node-npmlog                           0.0.4-1                                         all          Logger with custom levels and colored output for Node.js
ii  node-read-package-json                1.2.4-1                                         all          Read package.json for npm module for Node.js
ii  npm                                   3.5.2-0ubuntu4                                  all          package manager for Node.js
```

I thinks it's a issue with the npm version?
How should the export.js be updated?

All best

**Comment by jibon57** [comment]
How did you run it? Seems like you are running it different way or modified the code.

**Comment by levigo-systems** [comment]
We run it just like
```node export.js "https://xxxxxx/playback/presentation/2.0/playback.html?meetingId=xxxx" meeting.webm 15 true```

It's a fresh installation.

**Comment by jibon57** [comment]
Please follow this tuto to install `nodejs`: https://github.com/nodesource/distributions/blob/master/README.md#debinstall

**Comment by levigo-systems** [comment]
We installed v14.x and getting the following error
```
Error: Could not start Xvfb.
    at Xvfb.startSync (/root/bbb-recorder/node_modules/xvfb/index.js:84:17)
    at main (/root/bbb-recorder/export.js:43:18)
    at Object.<anonymous> (/root/bbb-recorder/export.js:157:1)
```

**Comment by jibon57** [comment]
Install all the required packages listed in readme file.

**Comment by levigo-systems** [comment]
They are all installed.

**Comment by levigo-systems** [comment]
After cleaning the moduls and run a fresh npm --install, it works.
