### ISSUE TITLE
Error: throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');

### ISSUE THREAD

**Issue by techie-explorer** [jibon57/bbb-recorder#43]
internal/util.js:214
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:214:11)
    at Object.<anonymous> (/home/bbb/bbb-recorder/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/bbb/bbb-recorder/node_modules/puppeteer/lib/cjs/node/BrowserFetcher.js:48:39)

**Comment by jibon57** [comment]
same https://github.com/jibon57/bbb-recorder/issues/42#issuecomment-656072972

**Comment by techie-explorer** [comment]
It worked, Thanks a lot!

**Comment by jibon57** [comment]
I am keeping it open as most of the user having this problem. Solution:

You are using older version of `nodejs`. Follow this to update: 

https://github.com/nodesource/distributions/blob/master/README.md#debinstall

**Comment by techie-explorer** [comment]
Yeah cool! I upgraded to 12.x and it worked fine.

**Comment by amg-web** [comment]
shall I use latest or specific version?

**Comment by amg-web** [comment]
I have also this /var/bigbluebutton/published/presentation/01e03e98b2d58d5b189e0c7c4592dc4b3fc94574-1591286409969/video/webcams.webm: No such file or directory

vebcams has mp4 extension
bbb 2.2.20

**Comment by amg-web** [comment]
bbb uses nodjs 8
are you sure upgrade does not break things?
it looks like record processing is not working, records is not published. Can somebody confirm?

**Comment by techie-explorer** [comment]
> bbb uses nodjs 8
> are you sure upgrade does not break things?
> it looks like record processing is not working, records is not published. Can somebody confirm?

Not sure if node version effects processing. I thought it was being used for playback only!
