### ISSUE TITLE
Error: Failed to launch the browser process! spawn /usr/bin/google-chrome ENOENT

### ISSUE THREAD

**Issue by tayyabsayyad** [jibon57/bbb-recorder#62]
Anybody has got this! 

Error: Failed to launch the browser process! spawn /usr/bin/google-chrome ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/tayyabali/bbb-recorder/node_modules/puppeteer/lib/Launcher.js:750:14)
    at ChildProcess.<anonymous> (/home/tayyabali/bbb-recorder/node_modules/puppeteer/lib/Launcher.js:741:65)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
^C

**Comment by jibon57** [comment]
make sure that you have install `xvfb` & all other dependencies.

**Comment by tayyabsayyad** [comment]
Thanks it got worked out!

**Comment by mirkahromi** [comment]
Can you please share your solution here @tayyabsayyad ?
