### ISSUE TITLE
Issue while running command - external server

### ISSUE THREAD

**Issue by navkumar987** [jibon57/bbb-recorder#69]
I have deployed your solution in a different server and when I am trying to run the command, I am getting below error, Could you help me to debug it.

```
const { copyToPath, playbackFile } = require('./env');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

Here is my .env file

```
rtmpUrl=rtmp://a.rtmp.youtube.com/live1/MyKey
ffmpegServer=ws://localhost
ffmpegServerPort=4000
auth=mZFZN4yc
copyToPath=/var/www/
playbackFile=playback.html
```

**Comment by navkumar987** [comment]
Node Version Problem, Solved by Upgrading the Node Version.
