### ISSUE TITLE
Error: Cannot find module '/root/export.js'

### ISSUE THREAD

**Issue by matinwd** [jibon57/bbb-recorder#91]
I am in the last section of your document and i typed this 

 node export.js "https://live.4baghamlak.ir/playback/presentation/2.0/playback.html?meetingId=test02" meeting.webm 10 true

But i got this error:

module.js:550
    throw err;
    ^

Error: Cannot find module '/root/export.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by jibon57** [comment]
Because you aren't in module directory.

**Comment by matinwd** [comment]
root@ubuntu-g1-6-16-75-at-1:~/bbb-recorder# cp .env.example .env
root@ubuntu-g1-6-16-75-at-1:~/bbb-recorder# node export.js "https://BBB_HOST/playback/presentation/2.0/playback.html?meetingId=MEETING_ID" meeting.webm 10 true
Error: Could not start Xvfb.
    at Xvfb.startSync (/root/bbb-recorder/node_modules/xvfb/index.js:84:17)
    at main (/root/bbb-recorder/export.js:45:18)
    at Object.<anonymous> (/root/bbb-recorder/export.js:160:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
(node:554) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of undefined
    at main (/root/bbb-recorder/export.js:151:14)
    at Object.<anonymous> (/root/bbb-recorder/export.js:160:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
(node:554) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:554) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
root@ubuntu-g1-6-16-75-at-1:~/bbb-recorder#

**Comment by matinwd** [comment]
I am in the bbb-recorder folder. I followed the Docs.
