### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Page crashed!

### ISSUE THREAD

**Issue by kuntiik** [jibon57/bbb-recorder#96]
Hello everyone,
I am trying to get this up and running. I modified the export.js file according to the file, that was pushed into Pull request (to make this program compatible with bbb 2.3), but I get this error. I am JS noob so maybe this is some easy to fix bug, but I am not able to figure it out. Thank you for any future help.

node export.js "https://bbb04.felk.cvut.cz/playback/presentation/2.3/0393a4ac2c9cab3db1483fbf3efc5d7af2398dd8-1621340701572\?meetingId\=0393a4ac2c9cab3db1483fbf3efc5d7af2398dd8-1621340701572" test.webm 100
(node:19775) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (/mnt/c/Users/kuntl/bbb-recorder/node_modules/puppeteer/lib/Page.js:213:24)
    at CDPSession.Page.client.on.event (/mnt/c/Users/kuntl/bbb-recorder/node_modules/puppeteer/lib/Page.js:122:56)
    at CDPSession.emit (events.js:198:13)
    at CDPSession._onMessage (/mnt/c/Users/kuntl/bbb-recorder/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/mnt/c/Users/kuntl/bbb-recorder/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocketTransport._ws.addEventListener.event (/mnt/c/Users/kuntl/bbb-recorder/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/mnt/c/Users/kuntl/bbb-recorder/node_modules/puppeteer/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/mnt/c/Users/kuntl/bbb-recorder/node_modules/puppeteer/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:198:13)
(node:19775) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19775) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jibon57** [comment]
Try latest version
